OpenXcom/OpenXcom

src/Geoscape/Globe.cpp, src/Ruleset/City.cpp, src/Ruleset/City.h
Small patch adding removing mess if you have lot of cities.
Every city have now new property `zoom` (def val 3) that determine on what minimum zoom level is require to show name of that city.
As bonus, some rogue white space clean up.
=> Cities zoom filter

bin/data/Ruleset/Xcom1Ruleset.rul, src/Engine/FlcPlayer.cpp, src/Engine/FlcPlayer.h, src/Menu/IntroState.cpp
Pressing a mouse button or a keyboard button should skip the video without waiting.
Corrected the video path, the default should be linux one.
Fixed a crash when no video is found.
Fixed black pixels in the Earth sequence, thanks to AndO3131.
=> Tftd video corrections.

src/Engine/FlcPlayer.cpp
This was causing a warning with GCC 4.8 on Ubuntu 14.04.
With the default of -Werror on, it was causing the build to fail (as it should).
Only the variable causing the warning was changed, other variables were not checked for use while uninitialized beyond compiler warnings.
=> Fixing uninitialized variable in new FlcPlayer code.

src/Geoscape/Globe.cpp
This time red dot is hidden too. Primarily because some times could be draw on top of another city name.
This is simples solution. Another possible solution would be change draw order of details, but this would require lot more changes than this.
=> Small improvement of city hiding

src/Basescape/ManageAlienContainmentState.cpp
ManageAlienContainmentState after loading. The field "Space available" shows wrong data. Must be -16.
One alien went to interrogation :)
If i want to kill 3 aliens, the field shows right data.
=> Fix: "space available" of the ManageAlienContainmentState

src/Savegame/BattleUnit.cpp
Current health is based on `_stats.health` if we compare it with `stats->health` we will get negative numbers and `setWoundRecovery` will be set negative. This break defense mission because of `getWounldRecowery() == 0`.
=> Fix bug with armor hp buff

src/Basescape/ManageAlienContainmentState.cpp
Looks like a programmer confused the conditions. Should be uplight only rows where all aliens will be killed.
Default Alien containment state:
If I want to kill several specimens:
How should be:
=> Fix: wrong color of rows in the ManageAlienContainmentState

bin/data/Ruleset/Xcom1Ruleset/armors.rul, src/Battlescape/UnitSprite.cpp, src/Battlescape/UnitSprite.h, src/Resource/XcomResourcePack.cpp, src/Ruleset/Armor.cpp, src/Ruleset/Armor.h, src/Savegame/BattleUnit.cpp, src/Savegame/BattleUnit.h, src/Savegame/SavedGame.cpp
Support for TFTD aquanauts recoloring.
One drawback it don't have default recoloring for all armors like current version.
Evey one who want use different colors for nationality in his sprite should add line like for `STR_NONE_UC`.
Additional I added option for aliens and civilians too. All code doing it is in last commit, can be skipped.
Only important change its do is move place where seed is loaded form save. This was done to preventing clobbering current seed by using `RNG` in `BattleUnit` constructor.
BTW for completion, do you want add option for recoloring corpses in battlescape and inventory?
=> Simple custom recolors

src/Savegame/MovingTarget.cpp, src/Savegame/SavedGame.cpp, src/Savegame/SerializationHelper.cpp, src/Savegame/SerializationHelper.h, src/Savegame/Target.cpp
http://openxcom.org/bugs/openxcom/issues/892 is the crash
https://code.google.com/p/yaml-cpp/issues/detail?id=197 -- this is an issue in yaml-cpp
My code works around the imprecision in yaml-cpp by pre-serializing doubles to hexfloat format. Old savegames remain compatible.
=> Fixed crash caused by serializing doubles imprecisely

src/Battlescape/BattlescapeGenerator.cpp, src/Battlescape/UnitSprite.cpp, src/Battlescape/UnitSprite.h, src/Resource/XcomResourcePack.cpp, src/Ruleset/Armor.cpp, src/Ruleset/Armor.h, src/Savegame/BattleUnit.cpp, src/Savegame/BattleUnit.h, src/Savegame/SavedBattleGame.cpp
I made some fix to ION armor on load because it's messy. Its mix colors form different color groups that is problematic for my recoloring and even worse for normal shading. Some colors used are form 9 group that don't have proper shades.
New recolor values used by aquanauts:
spriteFaceGroup: 14
spriteFaceColor: [160, 160, 64, 160, 160, 64, 160, 160] #M0 F0 M1 F1 M2 F2 M3 F3
spriteHairGroup: 4
spriteHairColor: [16, 16, 204, 160, 64, 200, 160, 64] #M0 F0 M1 F1 M2 F2 M3 F3
Added support for third color and color based on rank for mod proposes.
To made it work I made proper fix for faction of MC units. battle unit constructor is always call with proper fraction.
I find too bug in yaml that break saves. I used `Uint8` for saving values but sometimes its output value that it can load back (e.g. …
=> Improved recolor

src/Interface/Text.cpp, src/Interface/Text.h, src/Interface/TextList.cpp
There were two bugs here that I found and fixed while exploring the UI:
1) if the longest wrapped line in a row was not in the first column, the
rendered text would collide with the next rendered row
2) if a wrapped text element spanned more than two rows, it would be
scrolled incorrectly
The first I fixed by ensuring all elements in a row are set to the
height of the tallest element so draw() will pick up the correct Y delta
when incrementing the offset for the next row.
The second I fixed by replacing the "check row - 1" logic in draw()
(which could only handle wrapped text of two lines maximum) with a loop
that can handle wrapped text of arbitrary length.
=> Fix rendering of wrapped elements in TextLists

src/Battlescape/BattlescapeGenerator.cpp
Because possible situation, when turret cannot be mounted after mounting auxiliary weapons.
In this situation will be lost all ammo of main weapon.
By the way, in real world it will be very strange technological process. First mount auxiliary weapons (to the air around turret), then, if there was a place, mount turret and main weapon.
=> Fix: turret should be mounted before auxiliary weapons.

src/Battlescape/BattlescapeGenerator.cpp
Now if ilvl > max level then it use last level available.
Its fix problems when you try run two mods with different item levels.
=> Relax item level requirements

bin/standard/XcomUtil_Statstrings/XcomUtil_Statstrings.rul, src/Ruleset/StatString.cpp
This modifies two files and makes the Melee attribute available to XcomUtil's Custom StatStrings.
Tested by Meridian, Arthanor, & IvanDogovich
=> Add melee availability to statstring conditions

src/Engine/FileMap.cpp
this bug snuck in when I wrote the compatibility code for old mod formats.  it wasn't properly ignoring rulesets when the ignoreRulesets flag was set and the Ruleset directory exists
=> respect ignoreRulesets flag in old mod compat code

src/Engine/Language.cpp
so as not to spam the output logs
=> only output warnings about missing strings once

src/Engine/Options.cpp
this was no longer a good way to detect xcom2 since that particular file is now checked in.
=> improve xcom2 detection

src/Interface/TextList.cpp
the "_visibleRows - 1" fix prevented the arrow buttons on the last row from working.  this patch fixes the root cause -- the invalid calculation of endArrowIdx when the text item in the top row is only partially visible
=> fix off by one error AND handle last row's buttons

src/Battlescape/InventoryState.cpp
custom armors will fail the UFOGRAPH probe, which will cause
FileMap::mapFile to spit out a useless error message.  use the vfolder
lookup method to avoid the error message
=> don't spam the logs when probing for armor sprites

bin/standard/xcom1/font.rul, bin/standard/xcom2/font.rul, src/Resource/XcomResourcePack.cpp, src/Ruleset/Ruleset.cpp, src/Ruleset/Ruleset.h
This commit (re-)intoduces font externalization via mod support.
Modders who want create own font collection, needs to overwrite
"fontName" string (which is filename, placed in Language folder) in .rul file.
=> Externalize fonts via modding (second try)

README.md, bin/TFTD/README.txt, bin/UFO/README.txt, src/Engine/Options.cpp
- allows all external resource dirs to be loaded from the user folder
- make UFO and TFTD game detection routines more friendly so we can
still detect that the games are installed even on case sensitive files
where all files have been lcased (which was a popular way to get the game
running in OpenXcom 1.0 on Linux)
=> allow UFO and TFTD in the user folder

src/Savegame/Base.cpp
Hyperwave decoder has the rule "radarChance: 100".
https://github.com/SupSuper/OpenXcom/blob/master/bin/data/Ruleset/Xcom1Ruleset.rul#L1139
But this rule not used.
I suggest take this rule into account.
=> Feature: Hyperwave decoder sometimes cannot intercept transmissions.

src/Battlescape/BriefingState.cpp, src/Battlescape/BriefingState.h, src/Ruleset/AlienDeployment.cpp, src/Ruleset/AlienDeployment.h
This was a request from SupSuper to support the pre-T'leth cutscene.  Cutscenes can now be associated with briefing data and will be shown before the associated briefing screen.
=> support pre-mission cutscenes

src/Savegame/SaveConverter.cpp
Instead unique ranks converter pushes all ranks from all aliens.
For first 6 ranks that OK, but terrorists would becomes commanders instead, after this game crashes in Base Info screen as non existed alien do not have weight.
See http://openxcom.org/forum/index.php?topic=3677.msg46125 for actual issue.
=> Ranks compared with saved race instead rank.

src/Engine/Surface.cpp
We need copy 256 not 255 colors in palette.
This bug didn't surface because in 99.9% cases palettes are ignored.
=> Bug in palette copy

CMakeLists.txt, src/CMakeLists.txt
1) Find OpenGL package without relying on whether the pre-compiled dependencies (deps folder) are used. Removed the include directories variable for OpenGL, since they seem not to be referenced elsewhere.
2) YAML Debug library is now correctly linked for the debug configuration (produced compiler errors)
=> Fixes Compiling with pre-compiled dependencies

src/Engine/OpenGL.cpp
This reverts the OpenGL part of commit 038bb833378b38ca4751280ae5cf23d2db33e03e.  I don't know clang warnings that tried to fix, but the current code can't be right.  Every variable has a non-null address because it is a variable.  There is no such thing as a homeless variable.  So, `shader_support` always evaluates to true.  g++ righteously complains about this and (with -Werror) refuses to compile the code:
src/Engine/OpenGL.cpp:298:43: error: the address of ‘OpenXcom::glCreateProgram’ will always evaluate as ‘true’ [-Werror=address]
shader_support = &glCreateProgram && &glUseProgram && &glCreateShader
=> fix address errors

Makefile.am
Hi,
I'm working on packaging this for Debian (and the commercial data with `game-data-packager`)
I have the `install-data-local` rule fail because $(DESTDIR)$(pkgdatadir) doesn't exist.
It's maybe linked to the parallel build.
I guess a little `mkdir -p $(DESTDIR)$(pkgdatadir)` wouldn't hurt; even
if it's not needed for other environments.
Alexandre Detiste
PS:
Is this license really applicable ?
https://github.com/SupSuper/OpenXcom/blob/master/bin/standard/xcom1/Resources/Weapons/license.txt
Here is my current debian/rules:
```
#!/usr/bin/make -f
#export DH_VERBOSE=1
%:
dh $@ --parallel --with autotools-dev,autoreconf
#--buildsystem=qmake
override_dh_auto_configure:
./configure --prefix=/usr --bindir=/usr/games --disable-werror --without-docs
override_dh_auto_install:
mkdir -p …
```
=> Makefile.am: fix parallel build

src/Menu/MainMenuState.cpp, src/Menu/StartState.cpp
If a player has no ANIMS/FLOP_INT folders but doesn't disable playing the
intro, the resolution/scale won't be changed for the main menu. This patch moves
the code for resolution change to the GoToMainMenuState utility state.
=> Fix wrong resolution in main menu if intro is not present.

bin/standard/xcom1/interfaces.rul, bin/standard/xcom2/interfaces.rul, src/Battlescape/MedikitState.cpp
Since the medikit sprite is different from xcom1, the
users-without-keyboard-and-right-click (aka mobile users) are having
trouble getting away from this screen, since the exit button is now not in
an obvious position. This patch makes the right handle an exit button for
TFTD.
=> Make the "exit medikit screen" button moddable.

CMakeLists.txt
When cmake uses system yaml-cpp, it cannot compile project in debug mode
since YAMLCPP_LIBRARY_DEBUG is not initialized.
=> Fix underlinking compilation error in debug mode in Linux.

src/Ufopaedia/ArticleStateCraftWeapon.cpp
=> Show ammo capacity for craft weapons in UFOpaedia.

src/Engine/Logger.h
Fix crash when verboseLogging is enabled in config file and dump
verbose level into stderr console along with DEBUG.
=> Fix VERBOSE log level crash

src/Engine/Surface.cpp
Very handy for catching libpng warnings.
Don't forget to enable/disable verboseLogging in config.
=> Add verbose facility logging for loading images.

Makefile.am
faeeba46eef7b8819cfda404f2916b0e2971210a introduced filenames with spaces. `make install` chokes on those files because xargs thinks a file named "foo bar" is two files (foo and bar).
=> Handle spaces in filenames by avoiding xargs

CMakeLists.txt
OpenGL is only needed for the shaders.
The game itself runs fine without openGL (due to SDL backend).
=> Let cmake allow building even when openGL headers are not found.

src/Basescape/CraftArmorState.cpp, src/Basescape/CraftEquipmentState.cpp, src/Basescape/CraftWeaponsState.cpp, src/Basescape/ManageAlienContainmentState.cpp, src/Basescape/ManufactureStartState.cpp, src/Basescape/PurchaseState.cpp, src/Basescape/ResearchInfoState.cpp, src/Basescape/SackSoldierState.cpp, src/Basescape/SellState.cpp, src/Basescape/SoldierArmorState.cpp, src/Basescape/StoresState.cpp, src/Basescape/TransferItemsState.cpp, src/Battlescape/BattlescapeGenerator.cpp, src/Battlescape/DebriefingState.cpp, src/Geoscape/GeoscapeState.cpp, src/Geoscape/ItemsArrivingState.cpp, src/Menu/NewBattleState.cpp, src/Savegame/Base.cpp, src/Savegame/Base.h, src/Savegame/Craft.cpp, src/Savegame/Production.cpp, src/Savegame/SaveConverter.cpp, src/Savegame/SavedGame.cpp, src/Savegame/Transfer.cpp
Old name implied that the function would return all items on base, while it returns only those items
currently in stores (it does not return items assigned to craft and and items in transfer).
=> Refactor Base::getItems into Base::getStorageItems

src/Engine/Adlib/adlplayer.cpp
There are some cases where iChannel is larger than the array allocated
to it (12) - this then isn't checked before poking around in memory
causing shenanigans.
Noticed using -fsanitize=address in gcc
=> Fix memory corruption in adlplayer.cpp

src/Mod/AlienDeployment.cpp
compilation still has trouble
```
src/Mod/AlienDeployment.h:75:33: error: ‘OpenXcom::AlienDeployment::_durationMax’ will be initialized after [-Werror=reorder]
int _markerIcon, _durationMin, _durationMax, _minDepth, _maxDepth, _minSiteDepth, _maxSiteDepth;
^
src/Mod/AlienDeployment.h:72:14: error:   ‘std::string OpenXcom::AlienDeployment::_alert’ [-Werror=reorder]
std::string _alert, _alertBackground;
^
src/Mod/AlienDeployment.cpp:116:1: error:   when initialized here [-Werror=reorder]
AlienDeployment::AlienDeployment(const std::string &type) : _type(type), _width(0), _length(0), _height(0), _civilians(0), _shade(-1), _finalDestination(false), _markerIcon(-1), _durationMin(0), _durationMax(0),
^
```
=> Initialization order must match declaration order

bin/standard/xcom1/units.rul, bin/standard/xcom2/units.rul
After adding support for moddable deathsound (61c2601c628d99083669be613876b50b74e67a8e) by new logic, if you don't need death scream, you shouldn't define deathSound otherwise OpenXcom will crash with segfault.
=> Removing non-existed deathSound reference to BATTLE.CAT

.gitignore, Makefile.am, src/Basescape/SoldierDiaryMissionState.cpp, src/Basescape/SoldierDiaryOverviewState.cpp, src/Basescape/SoldierDiaryPerformanceState.cpp, src/Basescape/SoldierDiaryPerformanceState.h, src/Basescape/TransferItemsState.cpp, src/Geoscape/Globe.cpp, src/Mod/RuleCommendations.cpp, src/Savegame/BattleUnit.cpp, src/Savegame/BattleUnit.h, src/Savegame/SoldierDiary.cpp
Makefile typos
uninitialized variable (Globe.cpp)
added parentheses to fix operator order (&& comes before || by default)
constructor initializer reordering
unused variables
signed/unsigned comparisons
"narrowing conversion... from ‘double’ to ‘int’ inside { } is ill-formed in C++11" (TransferItemsState.cpp, old issue)
and retabbification
=> Lots of fixes to get things compiling

CMakeLists.txt, src/git_version.h.in
Another solution to PR #1067 
Previous version forces rebuild whole project after changing Git revision.
Now it should rebuild only 4 files that relies on version.h.
Additional feature:
You can define OPENXCOM_VERSION_STRING variable during configuration
to add your own string to version name. For example:
```cmake -DOPENXCOM_VERSION_STRING=" 2016-01-01"  <source-files>```
or
```cmake -DOPENXCOM_VERSION_STRING=" Xmas Edition" <source-files>``` 
Have fun.
=> Optimizing cmake building process

CMakeLists.txt, src/Savegame/SavedGame.cpp
Adds "-dirty" when build was based on sources with uncommitted
alterations (hence unknown to bug-hunters).
=> Describe worktree state in the version string.

src/Battlescape/BattlescapeGenerator.cpp
Fixed weapons should be always mounted to "hands".
Because if I sets "fixedWeapon: true", then I expect this weapon will be mounted to turret.
Because I cannot use the fixed weapon if they mounted to "backpack".
=> Fix: fixed weapons should be always mounted to "hands".

src/Battlescape/BattlescapeState.cpp, src/Battlescape/BattlescapeState.h
Sometimes good soldiers dies because of fatal wounds.
Sometimes good soldiers dies because of fatal wounds because player not know that this soldier has fatal wounds. Because good soldiers cannot speak.
This feature improves the game experience.
When unit has fatal wounds, his health bar will be flashing.
=> Feature: When unit has fatal wounds, his health bar will be flashing.

src/Battlescape/TileEngine.cpp
Running OpenXcom with gcc sanitizers finds new, interesting bugs. In this case, buffer overflow in height check.
Fix copied from different function in same file.
=> Buffer overflow fix

src/Battlescape/TileEngine.cpp
Size-10 array with 6 elements with only 4 ever accessed was here. Now it isn't
May have caused some units to be unseen when they should have been seen.
=> Underexposure of random units

src/Battlescape/MedikitState.cpp, src/Battlescape/MedikitState.h
Action menu already did the hard work (and shows it to user), so why not
make use of it.
Fixes bug where medikits do not behave as advertised when mods did not
set ``flatRate: true``.
=> Let medikits honor relative TU usage.

src/Battlescape/BattlescapeGame.cpp, src/Battlescape/PsiAttackBState.cpp, src/Savegame/BattleUnit.cpp, src/Savegame/BattleUnit.h
Forum user Countdown3 pointed these out to me.
The first commit uses a new var, _mindControllerID, to remember who last used a psi attack on a unit. Before hand, _murdererId was used, but of course this could be overridden if, for example, a mind controlled unit was shot. 
The second commit removes the setting of _mindControllerID from an if loop that ensured that duplicate entries were not added to a diary. The fact that a unit is psi attacking another unit should be remembered regardless of the number of the attack was done. This is important when multiple units are all psi attacking the same other unit.
=> Diary psi-related bugs

src/Interface/TextList.cpp
Fix selector not drawn on a mousepointer location when a list is (re)drawn via init().
In those cases getY() refers to the window surface, not the list surface.
Other functions assume it links to list surface.
=> Fix _selector after list(s) redrawn via init()

src/Battlescape/DebriefingState.cpp
Before, the diary mission state would not list what UFO or race attacked the player in a base defence mission. This fixes that! Probably. I suppose if there are two UFOs who are directly over the player's base then only the first one will be considered the attacker... but, what are the odds of that happening??
=> Track which race attacks you in a base defense

src/Interface/TextList.cpp
CTD on Ufopedia armor state - it adds empty rows in TextLists, which PR  #1093 doesn't handle adequately.
=> Fix BR 1202

src/Engine/Game.cpp
Moving a line downward because CTRL+G is not properly taken into account when used from the Options Video State.
`_states.back()->handle(&action);` has to be called after the "ctrl-g" key is processed.
Note: not sure how is handled `Options::debug`.
=> CTRL+G not properly taken into account when used from the Options Video State.

src/Engine/Adlib/adlplayer.cpp
There are only 16 elements, so index 16 is out-of-bounds
=> Fix out-of-bounds access in `instruments' array

src/Menu/OptionsBaseState.cpp
As the window cannot be moved if resolution is not changed, additional confirmation conditions are not appropriate, so it's better to remove them.
=> Rollback OptionsBaseState.cpp file.

cmake/modules/FindYaml_cpp.cmake
Hopefully a failure with message at build time is better, as this seems
a rather common problem
=> Add explicit check for broken yaml-cpp-0.5.2 in cmake

src/Engine/Options.cpp
On Linux the -config/-cfg argument is ignored if the -user argument isn't used at the same time.
This fixes the problem.
=> Don't reset _configFolder if it isn't necessary

src/Engine/Adlib/adlplayer.cpp, src/Savegame/SerializationHelper.cpp
This is technically undefined behaviour, -fsanitize=undefined warns
about it, and it could cause crashes on some platforms/compilers
=> Fix some unaligned accesses

src/Savegame/BattleUnit.cpp, src/Savegame/SoldierDiary.cpp
The destructor for a BattleUnit doesn't delete the BattleUnitKills if
there is a valid Soldier* for the unit, on the assumption that the
object will pass ownership to the SoldierDiary, but that ownership move
only occurs on the DebriefingState, so if you happen to leave a battle
in a way that doesn't show that it will leak (e.g. 'Abandon Game')
This changes the BattleUnit destructor to unconditionally destroy any
remaining BattleUnitKills objects, and the SoliderDiary::updateDiary()
function to empty the BattleUnit's list when it takes ownership.
=> Fix a leak of BattleUnitKills if the debrief is not shown

README.md, src/Engine/CrossPlatform.cpp
It's fine to also check in /usr/share/openxcom under FreeBSD, no need to
special case this. Update the docs to reflect that this is being checked
always (this was an omission from the Linux docs previously.)
Trim some trailing tabs while here.
=> Remove a FreeBSD specific ifdef and a redundant _WIN32 ifdef

CMakeLists.txt, src/CMakeLists.txt
Hi!
These patches unbreak building latest OpenXcom on OpenBSD.
=> OpenBSD also requires linking with libexecinfo

src/Engine/OpenGL.cpp
without this fix, this fails to compile with gcc due to -Werror=misleading-indentation:
```
src/Engine/OpenGL.cpp: In member function 'void OpenXcom::OpenGL::refresh(bool, unsigned int, unsigned int, unsigned int, unsigned int, int, int, int, int)':
src/Engine/OpenGL.cpp:154:3: error: this 'while' clause does not guard... [-Werror=misleading-indentation]
while (glGetError() != GL_NO_ERROR); // clear possible error from who knows where
^~~~~
src/Engine/OpenGL.cpp:155:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'while'
clear();
^~~~~
```
=> fixing misleading spacing resolving compile error with gcc

src/Geoscape/GraphsState.cpp
Country lines were drawn incorrectly.
When there was negative score, the *full* range was compared against only 8/9 of available chart space.
Technical:
1. the "check" is calculated against (0, range)
2. but "range" includes the portion below X axis too, so grids-- is not necessary/is wrong
3. the shift below X axis is done later (correctly)
=> Unified (and fixed) chart labeling algorithm

CMakeLists.txt
Should be no functional change for people who dont have exotic
filesystem layouts but offer flexibility to those who do.
=> Use the GNUInstallDirs for the .desktop and icons.

src/Menu/SetWindowedRootState.cpp
Some compilers couldn't handle this (e.g. on OSX, Android, ...)
=> Fix OSX build

src/Engine/Options.cpp
This makes the file much easier to compare between changes, and also makes it easier to version control.
Based on (OK, completely ripped off) [code by @hersh](https://github.com/jbeder/yaml-cpp/issues/169#issuecomment-219763811).
=> Save options.cfg ordered and with empty line at EOF

src/Ufopaedia/ArticleStateItem.cpp
Separate pedia articles with ammo info only didn't show number of pellets next to damage info.
=> Displaying shotgun pellets also in ammo articles

src/Engine/FlcPlayer.cpp, src/OpenXcom.2010.vcxproj, src/pch.h
Used these precompiled dependancies:
https://openxcom.org/forum/index.php/topic,3937.msg80377.html#msg80377
Had some warnings that I have now fixed.
Release compile now also have level 1 warnings (same as debug already had) now we don't have thousands of warnings.
Also we should have a link on this page to the precompiled dependancies:
http://ufopaedia.org/index.php/Compiling_with_Microsoft_Visual_C%2B%2B_(OpenXcom)
=> Vs2017 compile

src/Battlescape/BattlescapeState.cpp, src/Mod/AlienDeployment.cpp, src/Mod/AlienDeployment.h
The PlayStation version of UFO plays a special cutscene when a mission is aborted. This will allow mods to map a cutscene to this particular event.
=> Allow different cutscenes when aborting mission

src/Battlescape/Inventory.cpp, src/Battlescape/InventoryState.cpp
ensure fixed weapons can't be removed/added by ctrl-clicking or via
inventory template operations
This ensures tank-like units that show up on the equip screen (e.g. attack dogs in Final Mod Pack) can't have their fixed weapons replaced before battle.
=> fix behavior of fixed weapons in inventory screen

src/Engine/InteractiveSurface.cpp
For gcc 7.1 compilation causes a warning when ints are used as bools. We also enable warnings-as-errors. This causes the compilation to fail with the following error.
```
In file included from /usr/include/SDL/SDL_events.h:35:0,
from /usr/include/SDL/SDL.h:37,
from src/Engine/InteractiveSurface.h:20,
from src/Engine/InteractiveSurface.cpp:19:
src/Engine/InteractiveSurface.cpp: In Elementfunktion »void OpenXcom::InteractiveSurface::setButtonPressed(Uint8, bool)«:
/usr/include/SDL/SDL_mouse.h:122:27: Fehler: »<<« in booleschem Kontext, meinten Sie »<«? [-Werror=int-in-bool-context]
#define SDL_BUTTON(X)  (1 << ((X)-1))
~~~^~~~~~~~~~~
src/Engine/InteractiveSurface.cpp:79:41: Anmerkung: bei Substitution des Makros »SDL_BUTTON«
_buttonsPressed = _buttonsPressed & (!SDL_BUTTON(button)); …
```
=> Fixed int-in-bool-context warning/error for gcc 7.1

src/Engine/OpenGL.cpp, src/Engine/OpenGL.h
- Don't print "link error" to log when disabling shaders
- Simplify the shader lifecycle a bit (you can safely delete the shader objects after they're attached to a program)
- Handle zero-length logs on compile/link failure
=> OpenGL shader fixes

bin/common/SoldierName/Czech.nam
- fixed wrong spelling
(caused by incorrectly converted original names with diacritics)
- sorted alphabetically
- removed duplicates
- removed a few obviously non-Czech names
- trimmed trailing whitespaces
=> Fixed Czech name file

CMakeLists.txt
Surprised this is not an option already.  This makes building on linux systems while switching back and forth between git branches easier especially on more resource constrained systems.   This gets around monkeying with your system path or symbolic links to get ccache to work, but instead tell CMAKE to look for it.  This is off by default, so developers shouldn't be surprised by it.
=> add ccache detection for linux builds, off by default

src/Engine/Options.h, src/Menu/OptionsAudioState.cpp, src/Mod/Mod.cpp
This pull request has been created to implement [feature request #1397](https://openxcom.org/bugs/openxcom/issues/1397) filed on the OpenXcom bug tracker.
Currently, if "MIDI" is selected as the music format, songs from the GM.CAT file will be used if it exists, otherwise .MID files will be used. This means that if GM.CAT is present, .MID files cannot be used at all unless GM.CAT is removed from the SOUND subfolder of the game data directory. This also affects mods: if a mod provides music replacement via .MID files, they will not be played back if GM.CAT is present.
This change allows the user to choose between MIDI music from the GM.CAT file (if it exists) and separate .MID files. Besides the fact that the Steam version of UFO Defense comes with both GM.CAT and .MID files, this change …
=> Split "MIDI" music format to "MIDI (GM.CAT)" and "MIDI (MID files)"

bin/standard/xcom1/units.rul, src/Battlescape/UnitDieBState.cpp, src/Mod/Unit.cpp, src/Mod/Unit.h, src/Savegame/BattleUnit.cpp, src/Savegame/BattleUnit.h
This pull request has been created to implement [feature request #1398](https://openxcom.org/bugs/openxcom/issues/1398) filed on the OpenXcom bug tracker.
The logic which determines whether a unit can be captured or not is currently [hard-coded](https://github.com/SupSuper/OpenXcom/blob/master/src/Battlescape/UnitDieBState.cpp#L214). The unit can be captured alive if, and only if, it does not explode on death. There is no way to make a unit not capturable without making it explode on death, nor is it possible to make an alien which explodes on death capturable.
The proposed change introduces a new unit property called "capturable", which can take one of the three possible values:
* 0 (CAP_NOT_CAPTURABLE) - the unit cannot be captured alive by any means (it will simply die when it falls …
=> Allow mods to define whether a unit can be captured alive

src/Engine/OpenGL.cpp
at src/Engine/OpenGL.cpp L81:101 in non-apple platform
This raise warning, Debian8 x64 GCC 4.9.2-10, that treated as error as a result
of -Werror flag
full description of warnings:
<pre>
src/Engine/OpenGL.cpp: In member function ‘void OpenXcom::OpenGL::init(int, int)’:
src/Engine/OpenGL.cpp:436:40: error: the address of ‘OpenXcom::glCreateProgram’ will always evaluate as ‘true’ [-Werror=address]
shader_support = &glCreateProgram && &glDeleteProgram && &glUseProgram && &glCreateShader
^
src/Engine/OpenGL.cpp:436:40: error: the address of ‘OpenXcom::glDeleteProgram’ will always evaluate as ‘true’ [-Werror=address]
src/Engine/OpenGL.cpp:436:60: error: the address of ‘OpenXcom::glUseProgram’ will always evaluate as ‘true’ [-Werror=address]
shader_support = &glCreateProgram && &glDeleteProgram …
=> &glXXXVarName always has memory address value as it already initialized

src/Battlescape/BattlescapeGenerator.cpp, src/Battlescape/BattlescapeGenerator.h
This PR fixes [issue #1416](https://openxcom.org/bugs/openxcom/issues/1416) filed on the OpenXcom bug tracker.
In short: depth and music will now change between mission stages as they should.
In detail: this PR adds two new private methods to BattlescapeGenerator.cpp: setDepth and setMusic with code refactored into them from the run method. These methods are now called in the run method as well as the nextStage method in BattlescapeGenerator.cpp. Note that these methods have to know whether the mission is currently at the first stage or progressing to a new stage.
Notes about the setDepth method:
- First we need to check if the depth is already set (not 0) by the battle generator (original behavior). This also requires the mission to be at the first stage.
- We assume that an …
=> Fix depth and music not changing between stages in multi-stage missions

bin/standard/xcom2/terrains.rul
This PR is the proposed fix for [issue #1415](https://openxcom.org/bugs/openxcom/issues/1415) filed on the OpenXcom bug tracker.
In short: GRUNGE terrain seems to have wrong background music set in the standard ruleset (GMTACDRY instead of GMTACWET). It also doesn't have any depth set, which defaults to a depth of 0, though this is overridden by the alienDeployments.rul entry for the corresponding mission type (artifact site level 2). Nevertheless, I thought it would not hurt to specify the depth in this file also, considering it is specified for every other terrain where it differs from the default values, even if those terrains have it overridden during initialization.
BTW, considering the depth override, there seem to be certain inconsistencies between alienDeployments.rul and …
=> Fixed BGM and depth for the GRUNGE terrain

src/Basescape/MonthlyCostsState.cpp
Fixes small bug in monthly costs report where soldiers with a salary but can not be purchased (ex: custom starting soldiers) would not appear on the report.
=> Fix monthly costs display for soldier types with salary but not purchasable.

.travis.yml, Brewfile.travis
By using a Brewfile travis skips the `brew update` part which contributes significantly to the build time.
Contrary to the alternative (using homebrew packages inside `.travis.yml` a Brewfile allows to specify formulae options, needed for flac.
`yaml-cpp` no longer uses the `--static-lib` option (saves ~2 minutes).
The options: `--with-libmikmod --with-libvorbis` are part of he default formulae for `sdl_mixer` hence they are omitted.
Brewfile package information is available at: https://formulae.brew.sh/formula/
=> Reduce osx build time

src/Battlescape/DebriefingState.cpp
1. if civilians are not recoverable (e.g. vanilla), this was unreachable code
2. if civilians are recoverable (e.g. mods), this caused the unconscious ones to be counted twice
=> Fixed civilian scoring

scripts/build-openxcom
Hey
The script compiles OpenXcom on any distro. It is up to the user to
ensure the dependencies are in place.
To automatically clone/update git and compile:
./scripts/build-openxcom
I maintain similar compilation scripts for several projects to make compilation a breeze for anyone, without having to delve into often-outdated docs.
=> Added user-friendly compilation script

configure.ac
Having upgraded my system to Fedora 30, openxcom no longer builds because libdl.so (needed for dladdr, called in src/Engine/CrossPlatform.cpp) no longer gets pulled in by other libraries.  This patch will have configure check if it needs -ldl and include it if needed.
=> Look for dladdr in dl lib

bin/standard/xcom1/extraSprites.rul, bin/standard/xcom1/items.rul, bin/standard/xcom2/extraSprites.rul, bin/standard/xcom2/items.rul, bin/standard/xcom2/metadata.yml, src/Battlescape/BattlescapeGenerator.cpp, src/Engine/CrossPlatform.cpp, src/Engine/ModInfo.cpp, src/Engine/ModInfo.h, src/Engine/Options.cpp, src/Engine/Options.h, src/Engine/SoundSet.cpp, src/Engine/SoundSet.h, src/Engine/SurfaceSet.cpp, src/Engine/SurfaceSet.h, src/Mod/ExtraSounds.cpp, src/Mod/ExtraSounds.h, src/Mod/ExtraSprites.cpp, src/Mod/ExtraSprites.h, src/Mod/Mod.cpp, src/Mod/Mod.h, src/Mod/RuleBaseFacility.cpp, src/Mod/RuleCraft.cpp, src/Mod/RuleCraftWeapon.cpp, src/Mod/RuleItem.cpp, src/Mod/RuleItem.h, src/Mod/RuleSoldier.cpp, src/Mod/RuleTerrain.cpp, src/Mod/Unit.cpp
Refactor of handing mod sizes and surface indexes.
Breaking change:
* Mods that try access index outside space allocated for this mod will not load.
* Using negative index is illegal now (except `-1` that always mean "empty").
=> Update resorce load

src/Engine/CrossPlatform.cpp
On gnome/xfce based linux distributions [1] the error dialog is never shown when openxcom crashes. Instead it outputs a rather cryptic statement to the CLI:
```
(zenity:19512): Gtk-WARNING **: 02:23:42.257: Could not find the icon 'dialog-error-ltr'. The 'hicolor' theme was not found either, perhaps you need to install it.
...
```
Together with the text that is normally shown in the error dialog. This PR should fix that.
As always feedback is welcome
[1] Might be true for other desktop environments as well, haven't tested those though.
=> Fix zenity error dialog

src/Engine/OpenGL.cpp, src/Engine/OpenGL.h, src/pch.h
On recent Linux distributions [1]_ the `glext.h` copy as provided by SDL gives errors during compilation since it is no longer in sync with the one provided by mesa (which should be the one we want to use).
.. [1] In this case ubuntu but it is likely others will have the same 'problem'.
=> Fix GCC compile warnings on "GL_GLEXT_VERSION" redefined"

src/OpenXcom.2010.vcxproj
On a Chinese Windows system, the Visual Studio (2017) build output:
```
1>d:\prj\openxcom\src\basescape\manufacturestate.cpp(172): error C2001: newline in constant
1>d:\prj\openxcom\src\basescape\manufacturestate.cpp(173): error C2143: syntax error: missing ';' before 'else'
1>d:\prj\openxcom\src\basescape\manufacturestate.cpp(180): error C2001: newline in constant
1>d:\prj\openxcom\src\basescape\manufacturestate.cpp(181): error C2143: syntax error: missing ';' before '}'
```
I guess some non-English Windows systems will have the same problem.
FYI:
https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8
=> Add AdditionalOptions /utf-8 to OpenXcom.2010.vcxproj.

src/Savegame/Soldier.cpp
Problem
---
Currently, `monthsService` records in soldiers' diaries are unreliable (depend on save-load).
If a soldier doesn't have any missions (or commendations), then `monthsService` continues to increment in memory as the time passes (via `addMonthlyService`), but doesn't get saved to a save.
As a result, on reload every "desk job" soldiers' `monthsService` gets reset until they meet the criteria (e.g. go on a mission). This makes this value inconsistent (can be anything between 0 and the correct number after the first mission), which screws with statistics and commendations.
Proposed solution
---
Make a SoldierDiary that has `monthsService > 0` eligible to be saved in the savegame.
This ensures consistency after save-load with no other impacts that I can see.
=> Save diaries with non-zero monthsService

src/Engine/AdlibMusic.cpp
Because SDL volume goes through exponent calculation, 915e9987d8c097a8539d123fe83667ef21dc5d12 actually made it sound differently.
Now, check if SDL volume is zero or not, but still use `Options::musicVolume`
=> Fix the Adlib music volume after #1234

cmake/modules/FindYaml_cpp.cmake
The code uses #include <yaml-cpp/yaml.h>, this implies that yaml-cpp/yaml.h should be on the header search path, not yaml.h.
This also fixes support for Haiku introduced in 706cbc1d255d12fc8148ee274c7c9e48728ca326
=> FindYaml_cpp.cmake: search for yaml-cpp/yaml.h

src/Engine/FlcPlayer.cpp
It only reverts back to a work-around for the TFTD video files
=> FLC player now uses standard compliant behavior on default

src/Engine/InteractiveSurface.cpp
This PR fixes [bug 1481](https://openxcom.org/bugs/openxcom/issues/1481) reported on the old bug tracker.
**Synopsis**: It appears that SDL sometimes cannot recognize special keys and key combinations, depending on the input device. For example, my keyboard (Gigabyte Force K83) has an "Fn" key that can be used in combination with function keys F1-F12 to control volume, media playback etc. Unfortunately, doing this during an OpenXcom session causes it to trigger all unassigned actions from the controls menu. This happens because unassigned actions are actually bound to key code `SDLK_UNKNOWN`, and that's exactly what SDL returns.
This PR fixes the issue by returning early from `InteractiveSurface::onKeyboardPress` and `InteractiveSurface::onKeyboardRelease` if the provided key is …
=> Fixed: Do not bind keyboard events to unrecognized keys

src/Battlescape/BattlescapeGenerator.cpp
This PR fixes [bug 1480](https://openxcom.org/bugs/openxcom/issues/1480) reported on the old bug tracker.
**Synopsis**: When transitioning to the next stage in a multi-part mission, friendly units do not have their cache invalidated. This can lead to visual inconsistencies, and the most glaring one is that units who were floating in the air will still appear to be doing so. This problem can be rectified by forcibly invalidating the cache for all friendly units.
Note that in the current version (without these proposed changes), only the first unit will get its cache invalidated, unless one cycles through units on the inventory screen. This is because the inventory screen resets the selected unit's cache upon initialization. I can definitely confirm this is a caching problem, and the actual …
=> Invalidate cache for friendly units between mission stages

src/Battlescape/DebriefingState.cpp
Before this commit the game would not force the player to sell/destroy excess items/aliens after a mission under the following conditions:
* Too little items in base storage to restock the craft
* Alien containment has not enough free slots to hold all the captured live aliens
* User activated the option "storageLimitsEnforced"
After this commit the game behaves the same as you would normally see when there is enough to restock the craft.
--- Extra ---
Bug was introduced by c74a3522. 
By moving the `_noContainment` check the else clause for `_manageContainment` accidently became part of the `!_missingItems.empty()` control flow.
Just another testament that we are mere humans and not alien overlords ;)
=> Fix edge case for items and live alien recovery after a mission.

src/Menu/StatisticsState.cpp
This PR fixes [bug 1409](https://openxcom.org/bugs/openxcom/issues/1409) reported on the old bug tracker.
**Synopsis:** The value for "Average monthly rating" in the end-game statistics window is calculated incorrectly. It is derived only from the research scores vector, disregarding both XCOM and alien activity in regions. The proposed fix is to employ the same calculation as the one used in the geoscape graphs window: research score plus XCOM activity minus alien activity.
Do note that there are at least two other problems with this calculation:
- Only the last 12 months (at most) are used to calculate the average value. This is because the game is programmed to store at most 12 values of statistical data in each vector (I first mentioned this [on the …
=> Fixed average monthly rating calculation in StatisticsState

src/Battlescape/BattlescapeState.cpp, src/Battlescape/BattlescapeState.h
This PR resolves #1252 by allowing access to the built-in melee weapon of a unit from the battlescape UI.
**Synopsis:** See #1252 for details.
**TL;DR:** Lobstemen melee attack cannot be accessed when the unit is under player control. I have attempted to rectify the problem by allowing access to the special melee weapon through either of the two hand slots, provided that at least one of them is unoccupied. If both hand slots are empty, the right hand slot is used by default.
Note that all changes are UI only. Also, the active hand is only changed if the weapon being used is from the inventory, preserving the original behavior.
I have tested this in various scenarios and haven't encountered any unusual behavior so far. But it'd still be best if someone else could review the changes - there …
=> Allow player access to the built-in melee attack for Lobstermen

src/Interface/TextEdit.h
This is needed in addition to "CXXFLAGS=-O2 -g -std=c++11" and disabling
-Werror (due to unused functions, clang seems to be rather strict here).
Also, the setFocus method wasn't actually overridden, but hidden, which
makes clang warn and given the default of -Werror also error out.
This can probably be done in a smarter way ...
=> Fix build with clang 10.0.1 on FreeBSD

src/Battlescape/AIModule.cpp, src/Battlescape/AIModule.h, src/Savegame/SavedBattleGame.cpp
I received a report of AI freeze, which looks like this:
1. AI runs setupEscape() and decides it should escape to the same tile
as it currently occupies (for whatever reason); _escapeTUs is set to 1
2. AI evaluation sets _AIMode to 3 (=escape)
3. at the end of the think() cycle, _escapeTUs is not reset
(because there is no need to move)
Starting from this point setupEscape() is not executed anymore,
because _escapeTUs != 0. And as long as the enemy sees (or knows about)
xcom, it will not re-evaluate. Thus every turn it will just stay where
it is without doing anything (only thing it can do are reaction shots).
The freeze breaks only after turn 20 (or other forced re-evaluate).
Or after save and reload... because _escapeTUs is not saved
and will get reset back to 0 after reload.
=> Prevent AI frozen in place

src/Engine/OpenGL.h
I tried building on MacOS Catalina (10.15.7) with XCode 12.0 and noticed I get a lot of deprecation warnings for OpenGL e.g.
```
/OpenXcom/src/Engine/OpenGL.cpp:115:3: error: 'glGenTextures' is deprecated: first deprecated in macOS 10.14 - OpenGL
API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings) [-Werror,-Wdeprecated-declarations]
glGenTextures(1, &gltexture);
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl.h:2498:13: note: 
'glGenTextures' has been explicitly marked deprecated here
extern void glGenTextures (GLsizei n, GLuint *textures) OPENGL_DEPRECATED(10.0, 10.14);
```
These warnings then cause the build to fail (since treat warnings as errors is enabled …
=> Silence OpenGL deprecation warnings on MacOS 10.14+

docs/openxcom.6
When I viewed the new man page, I got error messages saying `<standard input>:14: missing \?` in the console. Then when I read the man page I noticed something odd in `SYNOPSIS` section:
```
SYNOPSIS
openxcom [] [-Enemy | -help] [-data path] [-user path] [-cfg path] [-master mod] [-KEY VALUE]
```
The source suggests the intention was to say `openxcom [-? | -help] ...`. Deleting the backslash before the question mark does that.
Also, `mandoc` linter told me that using `--` is deprecated and to use `\(em` instead - so I did that.
Tested in Slackware-14.2, Gentoo and Ubuntu 18.04. Display of synopsis was wrong in all environments I tested in, but only Slackware showed me the error quoted in the first paragraph.
=> Fix synopsis section in the manpage

bin/common/Shaders/CRT-Lottes-Warp.OpenGL.shader, bin/common/Shaders/CRT-Lottes.OpenGL.shader
Add Timothy Lottes' CRT shader from libretro in two versions,
one including screen curvature ('warp'), one without warp.
Why is this a good addition to OpenXcom?
- The default look of the shaders causes noticably less eye strain than the CRT style shaders already included in OpenXcom
- The shaders increase perceived detail fidelity for most sprites in OpenXcom (take a look at [the libretro shader overview](https://docs.libretro.com/shader/crt/)) compared to a simple upscaling; especially compared to upscaling with linear filtering
- They are a solid approximation of an authentic 90s look
- The look of the shaders can be easily and dramatically altered by tweaking preprocessor defines
=> Add two CRT style OpenGL shaders

.github/workflows/ci.yml, docs/CMakeLists.txt, src/CMakeLists.txt
Reported by: @MeridianOXC
The manpage is pretty useless under Windows and also for the macOS `dmg`
archives. The `make install` target could also use some more work, but
at least it's working now.
CPack could potentially be used, but would need a lot of work and the
current GH artifact build step is actually superior.
While here, use the proper NPROC value for all runners (except windows,
which falls back to 2). Linux needs sudo to install, Win/Mac don't.
=> Install the manpage only for Linux/*BSD, run `make install` during CI runs

src/Savegame/SavedBattleGame.cpp
OXCE is now saving also special weapons
(e.g. ALIEN_PSI_WEAPON or STR_LOBSTERMAN_MELEE_WEAPON)
These need to be skipped when loaded in OXC.
=> Compatibility with OXCE saves

src/Battlescape/Map.cpp, src/Battlescape/ProjectileFlyBState.cpp, src/Battlescape/TileEngine.cpp, src/Battlescape/TileEngine.h, src/Mod/RuleItem.cpp, src/Mod/RuleItem.h
Updated ONLY the calculations related to maxRange attribute of ranged weapons.
These calculations don't exist in the OG, relevant only for mods.
All other distance calculations were unchanged,
difference of +/-1 doesn't mean much in them anyway.
=> More precise distance calculation for 2x2 units

src/Engine/Zoom.cpp
MCST E2K (Elbrus 2000) - this is VLIW/EPIC architecture, like Intel Itanium (IA-64) architecture.
Ref: https://en.wikipedia.org/wiki/Elbrus_2000
e2k architecture has half native / half software support of most Intel/AMD SIMD
e.g. MMX/SSE/SSE2/SSE3/SSSE3/SSE4.1/SSE4.2/AES/AVX/AVX2 & 3DNow!/SSE4a/XOP/FMA4
This PR fixes the error "`__get_cpuid is undefined`" (line 637: error # 20), because e2k does not have an x86 CPUID instruction.
=> E2K: fixed build by MCST lcc compiler

src/Engine/Zoom.cpp
Made a slight improvement to the architecture detection algorithm in the `Zoom::haveSSE2()` function.
=> src/Engine/Zoom.cpp: updated Zoom::haveSSE2 check for e2k

src/Battlescape/BattlescapeGame.cpp, src/Battlescape/BattlescapeState.cpp
=> Fix soldier stats display when walking/shooting

CMakeLists.txt, cmake/modules/BuildType.cmake, docs/CMakeLists.txt
This should help with the transition from autotools where that is the
default. It should stop issues like #1284 and #1292 and these can be
considered closed.
=> Set the default cmake build type to Release

bin/common/Language/en-GB.yml, bin/common/Language/en-US.yml, src/Engine/ModInfo.cpp, src/Engine/ModInfo.h, src/Menu/ModConfirmExtendedState.cpp, src/Menu/ModConfirmExtendedState.h, src/Menu/ModListState.cpp, src/Savegame/SavedGame.cpp, src/version.h
Option for mods to define what "engine" of OXC mode require.
Now we have at least two version Extended and FtA and soon there could be more.
As different engines can support different set of mechanics, in some cases incompatible, we need universal
way to distinguish between them.
`supportedEngines` declare list of other engines that are supported (like FtA could support mods from Extended)
`OPENXCOM_VERSION_ENGINE` Is name of current engine.
=> Add more support for diffrent OXC engine versions

docs/CMakeLists.txt
Use the built-in module GNUInstallDirs ([doc link](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html)) to determine install path, which provides sane defaults per OS, as well as allowing overriding by package maintainers.
For example, one can override the default by specifying `cmake -DCMAKE_INSTALL_MANDIR=<path>` (e.g. "share/man" or "/var/lib/manpages/foo").
This is a partial revert of f8d860d7727ec6c7f8eed2d9e4cf9f83725d17a0 (fixes the path rather than removing it).
To address the other complaint in the commit message re: compression: As a package maintainer myself, I've seen very few install scripts that compress man pages. In fact, when it does happen, the compression method used is often wrong (default compression vs. max), or geared toward one specific distro/OS (e.g. …
=> Add corrected man page installation

src/Battlescape/DebriefingState.cpp, src/Menu/ModListState.h
This removes an unused field and fixes the initialization order in a ctor.
=> Fix build warnings on recent Clang

src/Interface/TextList.cpp
This PR causes `TextList::scrollTo()` to return early when scrolling is not needed.
This should prevent a 'bug' where lines go missing when programmatically trying to scroll lists smaller than allocated for.
-- edit --
Please disregard last line of commit message. I've misinterpreted original behavior.
Unintentional hiding of lines due to scroll still seems like an error to me though.
=> Prevent lines going missing when trying to scroll when not needed.

src/Mod/Mod.cpp, src/Mod/RuleTerrain.cpp
When rule is removed object stay in memory not deleted and effective leak memory.
As this happens only during load and mode need use `delete:`, amount of leaked memory is limited.
=> Fix memory leak on rule `delete:`

src/Engine/CrossPlatform.cpp
On linux, for run openxcom need change dir to 'bin', else it not work.
```shell
[ERROR] Failed to open directory: common
```
=> On linux, add absolute path of 'bin' folder

src/Battlescape/TileEngine.cpp
If below tile do not have floor whole test would be `false` and this could make GravLift floor above consider not hit.
(backport of commit 29f6bc520c9ef374f0ec701694d5e78c75dd7ea1)
=> Fix possible bug when tile below GravLift was void

src/Engine/GraphSubset.h, src/Engine/Options.cpp, src/Engine/Options.inc.h, src/Engine/ShaderDrawHelper.h, src/Geoscape/Cord.h, src/Geoscape/Globe.cpp
Some users have "unreasonable" screen sizes like 5120x2160, this scale poorly with globe cache.
Added hidden config to disable cache.
=> Fix globe memory allocation

src/Battlescape/InventoryState.cpp, src/Ufopaedia/ArticleStateArmor.cpp
https://openxcom.org/forum/index.php/topic,2027.msg149369.html#msg149369
=> Unified usage of Armor.spriteInv across all UIs

cmake/modules/PostprocessBundle.cmake
Homebrew on macOS arm64 lives in `/opt/homebrew` per default. Add `/opt/homebrew/lib` to PostprocessBundle.cmake's `extra_dirs`. Without this, `libsharpyuv.0.dylib` cannot be found during bundeling resulting in the following error:
```
CMake Error at /Users/xxx/Sources/OpenXcom/cmake/modules/PostprocessBundle.cmake:44 (_message):
otool -l failed: 1
error: /Library/Developer/CommandLineTools/usr/bin/otool-classic: can't
open file: @rpath/libsharpyuv.0.dylib (No such file or directory)
Call Stack (most recent call first):
/opt/homebrew/Cellar/cmake/3.27.4/share/cmake/Modules/BundleUtilities.cmake:458 (message)
/opt/homebrew/Cellar/cmake/3.27.4/share/cmake/Modules/BundleUtilities.cmake:527 (get_item_rpaths)
/opt/homebrew/Cellar/cmake/3.27.4/share/cmake/Modules/BundleUtilities.cmake:649 …
```
=> Update PostprocessBundle.cmake to include /opt/homebrew/lib

src/Battlescape/TileEngine.cpp
Sometimes TileEngine::calculateLineVoxel() successfully creates the trajectory to voxel inside a unit, but returns V_EMPTY instead of V_UNIT. As it turned out, LOFTemps data is stored in memory in "right" direction, with positive X axis from left to right, but (1 << x) in code counts X axis in negative direction, from right to left. LOFTemp becomes [effectively inverted from left to right](https://cdn.discordapp.com/attachments/292085473890009088/1138261841575948348/image.png), which moves unit slightly to the left. For terrain code, this effect negated by inverting X axis beforehand, just like that:
`int x = 15 - voxel.x%16;`
`int y = voxel.y%16;`
but the unit check does:
`int x = voxel.x%16;`
`int y = voxel.y%16;`
[Also, in original X-Com it was 0x8000 >> …
=> Fix bug with all units' voxels flipped relative to Y axis

src/Geoscape/GraphsState.cpp
Set lower limits and remove filter to only consider it when above 0.
There was merge-conflict about:
if (y >=180) y = 180;
if (y <= 45) y = 45;
This isn't from me. Likely from OXCE and likely makes sense to have too.		If not, remove that.
=> Fixed a bug where the TOTAL of X-Com-Activities in Areas and Countries wouldn't display negative values.

src/Menu/OptionsBaseState.cpp
When using `SDLcompat-1.2.68` the "Grab Mouse" option was not honored after switching from fullscreen to a windowed mode.
This PR should fix that behavior, by setting that option **after** the display reset.
=> Fix a scenario where mouse could not leave the window after switching from fullscreen to a windowed mode.
