src/Geoscape/UfoDetectedState.cpp, src/Geoscape/UfoDetectedState.h, src/Menu/OptionsAdvancedState.h
Private fields were defined and forgotten, apparently. Off with them.
=> Letting go of unused variables.

src/CMakeLists.txt
Added missing Ruleset/RuleMusic.{h,cpp}
=> Fix project files for CMake

bin/data/Ruleset/Xcom1Ruleset/alienMissions.rul, src/Battlescape/BattlescapeGenerator.cpp, src/Ruleset/RuleAlienMission.cpp, src/Ruleset/RuleAlienMission.h, src/Ruleset/RuleUfo.cpp, src/Ruleset/RuleUfo.h, src/Ruleset/Ruleset.cpp, src/Savegame/AlienMission.cpp, src/Savegame/Ufo.cpp, src/Savegame/Ufo.h
New field `specialUfo` used my missions to determine how handle different UFO types.
Retaliation: ufo of this type is spawn.
Supply: ufo of this type is transport craft.
Terror: ufo of this type can create terror site.
Additionally I made small code clean up.
=> Alien mission

src/Savegame/CraftWeapon.cpp
http://openxcom.org/bugs/openxcom/issues/878
=> Fix: reloading bug #878

bin/data/Ruleset/Xcom1Ruleset/vars.rul, src/Battlescape/AlienBAIState.cpp, src/Ruleset/Ruleset.cpp, src/Ruleset/Ruleset.h
Topic: http://openxcom.org/forum/index.php/topic,3219.30.html
Unhardcoded first turn when AI can use grenades or Blaster launcher.
=> Feature: unhardcoded first turn when AI can use grenades.

src/Engine/FileMap.cpp, src/Engine/FileMap.h, src/Engine/Game.cpp, src/Engine/Options.cpp
reinstate 'badmods' functionality.  also outputs a more friendly error message.
=> disable mods that have bad rulesets

bin/TFTD/README.txt
=> mention ANIMS directory for TFTD

README.md, src/Engine/Options.cpp
to allow the commandline param to line up with what the folder is called
=> allow -config as an alias to -cfg

src/Engine/Language.cpp
it was a case sensitivity issue
=> fix mapping of language ids to names

bin/standard/Aliens_Pick_Up_Weapons_TFTD/Aliens_Pick_Up_Weapons.rul, bin/standard/Aliens_Pick_Up_Weapons_TFTD/metadata.yml, bin/standard/Limit_Craft_Item_Capacities_TFTD/Limit_Craft_Item_Capacities.rul, bin/standard/Limit_Craft_Item_Capacities_TFTD/metadata.yml, bin/standard/UFOextender_Gun_Melee_TFTD/UFOextender_Gun_Melee.rul, bin/standard/UFOextender_Gun_Melee_TFTD/metadata.yml, bin/standard/UFOextender_Psionic_Line_Of_Fire_TFTD/UFOextender_Psionic_Line_Of_Fire.rul, bin/standard/UFOextender_Psionic_Line_Of_Fire_TFTD/metadata.yml, bin/standard/XcomUtil_High_Explosive_Damage_TFTD/XcomUtil_High_Explosive_Damage.rul, bin/standard/XcomUtil_High_Explosive_Damage_TFTD/metadata.yml, bin/standard/XcomUtil_Pistol_Auto_Shot_TFTD/XcomUtil_Pistol_Auto_Shot.rul, bin/standard/XcomUtil_Pistol_Auto_Shot_TFTD/metadata.yml, bin/standard/XcomUtil_Starting_Defensive_Base_TFTD/XcomUtil_Starting_Defensive_Base.rul, bin/standard/XcomUtil_Starting_Defensive_Base_TFTD/metadata.yml, bin/standard/XcomUtil_Starting_Defensive_Improved_Base_TFTD/XcomUtil_Starting_Defensive_Improved_Base.rul, bin/standard/XcomUtil_Starting_Defensive_Improved_Base_TFTD/metadata.yml, bin/standard/XcomUtil_Starting_Improved_Base_TFTD/XcomUtil_Starting_Improved_Base.rul, bin/standard/XcomUtil_Starting_Improved_Base_TFTD/metadata.yml
A first pass at making TFTD conversions for standard mods.
=> Feature: TFTD standard mod conversions

.travis.yml
Opening this up.  Hold off on merging until we get all packages whitelisted with travis.
We're waiting on:
- https://github.com/travis-ci/apt-package-whitelist/issues/715
- https://github.com/travis-ci/apt-package-whitelist/issues/1000
=> Switching to travis container builds for linux.

src/Geoscape/NewPossibleResearchState.cpp
=> Small fix to New research available screen.

src/Interface/Text.cpp
While working on some item screens I noted that wordwrap of ammo did not honour existing indentation.
This pull request should result in:
When wrapping on word boundaries is in effect, and:
When wrapping inside words is in effect.
Please note that the code to activate word-wrapping inside lists is not included.
=> Let wordwrap honor existing indentation.

src/Battlescape/Pathfinding.cpp, src/Battlescape/PsiAttackBState.cpp, src/Battlescape/TileEngine.cpp, src/Engine/Screen.cpp, src/Interface/TextButton.cpp
And one actual copy-paste bug.
That function wasn't used anywhere, so it wasn't found earlier.
=> Suspected things found by PVC-Studio

src/Mod/Armor.cpp, src/Savegame/BattleUnit.cpp, src/Savegame/SavedBattleGame.cpp
Deals with things described in http://openxcom.org/bugs/openxcom/issues/1162
by checking for -1 in rankInt before using it as an index.
=> Fixes buffer overflow

src/Battlescape/BattlescapeGenerator.cpp, src/Battlescape/MedikitState.cpp, src/Mod/Mod.cpp
`make ` would fail because of "all warnings being treated as errors"
=> Fix gcc compiler warnings

src/Basescape/SoldierDiaryMissionState.cpp, src/Basescape/SoldierDiaryMissionState.h
I created an init() function in the SoldierDiaryMissionState and moved stuff there, then added Next and Previous buttons. I did some copy pasting at lines 120 for the .cpp... I think I did it right, given that nothing crashed :D
=> Added Next and Prev buttons to the diary mission info screen

bin/common/Language/en-GB.yml, bin/common/Language/en-US.yml, src/Basescape/SoldierDiaryPerformanceState.cpp, src/Savegame/SoldierDiary.cpp, src/Savegame/SoldierDiary.h
In the Soldier Performance state, where kill totals are listed, an accuracy stat is now listed and replaces the panic stat. 
A global kill-share % was tested, but soldiers, on average, got 0% of the kills... leading me to conclude that the invasion was met with no resistance...
=> Diary accuracy

src/Engine/Language.cpp
Behavior before this PR was to treat those texts as being non-existing.
This could lead to confusion since they do actually exist in the translation files.
=> Warn if pluralization is used on a text that does not support it.

src/Basescape/SoldierDiaryPerformanceState.cpp, src/Battlescape/DebriefingState.cpp, src/Geoscape/MonthlyReportState.cpp, src/Savegame/MissionStatistics.h, src/Savegame/SoldierDiary.cpp, src/Savegame/SoldierDiary.h
This PR removes 10 or so items per soldier from the save file that can be otherwise calculated from the kills that are already saved.
*It's giving me a 'can't merge error', but I can't find out why on my end. I will PR this anyway, and see what I am told... also, I tried resetting my HEAD so there weren't 20 little commits.. but that didn't work either? I'll leave this up so you can at least review this.
=> Diary save bloat

.gitignore, src/Battlescape/Pathfinding.cpp, src/Battlescape/UnitFallBState.cpp, src/Engine/Language.cpp, src/Menu/ListLoadState.cpp, src/Mod/MapBlock.cpp
Missing include <algorithm> in supplementary cpp file.
=> Missing includes

src/CMakeLists.txt
* Changed *.cpp files, affected by last commit, fixes building.
* Stripped header files from CMakeLists.txt, they don't need to be here
=> Cmake improvements

src/Battlescape/DebriefingState.cpp, src/Savegame/AlienMission.cpp
A set of patch that fixes -Werror problems. I tried to compile the vanilla code on Ubuntu 14.04 but surprisingly the error doesn't pops out but on other system that are maybe more restrictive.
I'm running Void Linux with gcc 4.9.4 and cmake 3.6.1
=> Fix werror

src/Basescape/BaseView.cpp, src/Basescape/CraftInfoState.cpp, src/Interface/TextEdit.cpp, src/Interface/TextList.cpp
Solving it one place at a time.
=> Hardest problem is naming

xcode/README.md
Was leading to brew error
Error: No available formula with the name "—-with-static-lib"
=> Fixed a typo (the first hyphen wasn't)

src/Engine/OpenGL.cpp
Without this, *all* opengl shaders would fallback to 'no shader'....
I'll be available for a public flogging Friday.
=> Fix opengl program attach

src/Engine/OpenGL.cpp
This isn't needed, and shouldn't have made it to the merge request.
Sorry :)
=> Remove a LOG_WARNING printing the shader source

README.md
I noticed that this link was dead in the README so I updated it.
=> Updated dead link to yaml-cpp in README.md.

src/Savegame/MovingTarget.cpp
The hack/simple fix keeps the interceptor from looking ahead more than
halfway across the globe. The wrong way interception bug problem is caused
by that calculateMeetPoint may otherwise find an intercept point more than
halfway across the globe, and then calculateSpeed takes the shortest path
to it, which is the wrong way.
However, due to its simplicity, this fix will have trouble if an interceptor
is set to intercept a UFO that is on the far side of the world and is moving
slowly enough that the intercept point is also on the far side. It will take
the long way around in that case instead of meeting the UFO head on. It also
won't optimally intercept a faster UFO heading towards the interceptor at an
angle.
=> Fix for intercept bug: http://openxcom.org/bugs/openxcom/issues/1268

src/Battlescape/DebriefingState.cpp
clean up warning from stat increase report commit.  no logic changes.
=> clean up unused var warning

src/Basescape/CraftArmorState.cpp, src/Battlescape/DebriefingState.cpp, src/Mod/RuleCommendations.cpp, src/Mod/RuleCommendations.h, src/Savegame/SoldierDiary.cpp, src/Savegame/SoldierDiary.h
I added one include in order to be able to compile. Something to do with using yaml-cpp 0.5.3.
Converting _killCriteria from a map to a pair is the primary fix, and having now functional code exposed another hole, which was fixed with the addition of the bool andCriteriaMet.
A sanity check was added at line 377 of SoldierDiary.cpp
=> Commendations fix

src/Geoscape/GraphsState.cpp
=> Fix for last region/country button not being displayed

bin/standard/xcom1/converter.rul, src/Basescape/NewResearchListState.cpp, src/Geoscape/GeoscapeState.cpp, src/Geoscape/NewPossibleResearchState.cpp, src/Menu/NewBattleState.cpp, src/Mod/RuleResearch.cpp, src/Mod/RuleResearch.h, src/Savegame/SaveConverter.cpp, src/Savegame/SavedGame.cpp, src/Savegame/SavedGame.h
https://openxcom.org/forum/index.php/topic,5536.0.html
=> Research code fixes and refactoring

src/Basescape/BaseInfoState.cpp, src/Mod/Mod.cpp
https://openxcom.org/forum/index.php/topic,5630.0.html
=> Fix variable initialization

src/Basescape/SoldierDiaryOverviewState.cpp, src/Basescape/SoldierDiaryPerformanceState.cpp, src/Battlescape/CommendationLateState.cpp, src/Battlescape/CommendationState.cpp, src/Mod/Mod.cpp, src/Mod/Mod.h, src/Savegame/Soldier.cpp, src/Savegame/SoldierDiary.cpp, src/Savegame/SoldierDiary.h
Prevents CTD when upgrading commendations mod
=> Don't load non-existing commendations

m4/ax_check_gl.m4, m4/ax_restore_flags_with_prefix.m4, m4/ax_save_flags_with_prefix.m4
Note one tiny thing might be sensible to run something along following lines in .travis.yml but since you already have quite large matrix I am not sure if you wanna do it:
```bash
sh autogen.sh
mkdir build
pushd build
../configure
make distcheck
popd
```
The make distcheck generates release-able tarball and ensures that such tarball is still installable and uninstallable without any issues.
=> Update ax_check_gl from autoconf-archive

src/Battlescape/AIModule.cpp, src/Battlescape/BattlescapeGame.cpp, src/Battlescape/Map.cpp, src/Battlescape/Map.h, src/Battlescape/ProjectileFlyBState.cpp, src/Battlescape/TileEngine.cpp, src/Battlescape/TileEngine.h, src/Mod/MapData.h, src/Savegame/Tile.cpp, src/Savegame/Tile.h
Backported from OXCE.
I'll just leave it here, in case anyone wanted to include it in their OpenXcom fork.
=> Obstacle indicator

bin/standard/xcom2/vars.rul, src/Mod/Mod.cpp, src/Mod/Mod.h
Fix some problems when loading offset for surfaces and sounds from constants node.
=> Constants loading refactor

.github/workflows/ci.yml, README.md
Adds unified GitHub build jobs for Linux, Windows & macOS.
=> GitHub workflow for CI

bin/standard/xcom1/research.rul, bin/standard/xcom2/research.rul, src/Savegame/AlienStrategy.cpp, src/Savegame/AlienStrategy.h, src/Savegame/SaveConverter.cpp
=> Save converter fixes

src/Basescape/ManufactureStartState.cpp, src/Mod/RuleManufacture.cpp, src/Mod/RuleManufacture.h, src/Savegame/Production.cpp
=> Unified production monetary cost check

src/Battlescape/BattlescapeGame.cpp
=> Prevent psionic capture of uncapturable units

src/Savegame/AlienMission.cpp
=> Mission zone fix

src/Battlescape/BattlescapeState.cpp, src/Battlescape/MiniMapView.cpp
continuation of: https://github.com/OpenXcom/OpenXcom/commit/1f837a1c6cc5d315d1088dbb33e6a03757a1d5c0
=> fix drag scrolling with black borders, part 2

src/Savegame/SoldierDiary.cpp
Addresses https://github.com/OpenXcom/OpenXcom/issues/1302 and https://github.com/OpenXcom/OpenXcom/issues/1287
* woundsHealedTotal wasn't tallying totals
* killsWithCriteria<...> commendations were tallying results awkwardly, getting tallies for each OR criteria block separately from other blocks, which resulted in "best of" tallying across all OR blocks, rather than "total of" which was the presumed behavior by Commendations mod logic as well as other mods such as X-Piratez
This code produces mostly the same end result as what @karadoc did [here.](https://github.com/karadoc/OpenXcom/commit/a6055080d2f38602191fe3d5a3c4dd8329cd5854) The difference is in algorithms, as well as addressing https://github.com/OpenXcom/OpenXcom/issues/1287, as they both are about commendation statistics bugs.
=> fix statistics calculation for commendations

bin/common/SoldierName/Norwegian.nam
Inge is a male name in Norwegian
Quisling is not used anymore
=> Norwegian name file update

src/main.cpp
Also, the _DEBUG check doesn't seem to work for CMake builds.
=> Change #ifdef check for debug builds to more compatible version.

src/Engine/Action.cpp
Looks like when originally written the descriptions for several methods were copy+pasted and then not updated. This updates the comments to be consistent with the methods' intents.
This only changes method comments, so there shouldn't be any functional changes.
=> Fix copy-paste typos in Action.cpp

src/Mod/RuleCountry.cpp, src/Mod/RuleRegion.cpp
=> Fix earth pole region error

src/Engine/CrossPlatform.cpp, src/Engine/Options.cpp
Some improvements in handling command line to make it more conforming to typical command line tools.
=> Command line fixes

src/Mod/UfoTrajectory.h, src/Savegame/AlienMission.cpp
=> Float math not needed here

.gitignore, src/Battlescape/Pathfinding.cpp
https://openxcom.org/forum/index.php?topic=12589.0
=> Improve rubble-wall handling in pathfinding
